#!/usr/bin/env python3
"""Resolve citations against their primary sources — the ONLINE half of verification.

``make check`` is offline, so it cannot ask arXiv whether a paper exists. This script can.
It asks the primary service for every handle a claim or work names, and records what came
back (title · service · date) in ``data/resolutions.yml``. The offline gate
(``tools/check.py`` via ``core/citations.py``) then refuses any ``verified: true`` whose
handles have no recorded resolution.

Resolving a handle proves the source EXISTS and says what it is called. Whether it
SUPPORTS the claim is still a human judgment — so this script never flips ``verified``;
it only makes the flag checkable.

    python3 scripts/resolve.py                 # resolve every unrecorded handle in the spine
    python3 scripts/resolve.py --refs arXiv:2310.12921 doi:10.1056/nejmoa1907863
                                               # look a handle up without recording it
Services: arXiv (its DataCite DOI, then the export API) · doi.org content negotiation (Crossref + DataCite) ·
Open Library (ISBN) · the URL itself (HTTP 200 + <title>).
"""

from __future__ import annotations

import argparse
import datetime as dt
import html
import json
import re
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from control_anything.core.citations import extract_refs, index_resolutions, work_source  # noqa: E402

RESOLUTIONS = ROOT / "data" / "resolutions.yml"
UA = "control-anything-resolver/0.1 (+https://github.com/wjlgatech/control-anything)"
HEADER = """\
# What each primary source returned when scripts/resolve.py asked it.
#
# GENERATED by `make resolve` (the one networked target). Do not hand-edit a row: a typed
# title is exactly the unearned `verified: true` this file exists to replace. The offline
# gate refuses any verified claim or work whose handles are missing here.
#
# A row proves the source EXISTS and records its real title. Whether it SUPPORTS the claim
# is still a human judgment, made in data/claims.yml and data/works.yml.
"""


def _get(url: str, accept: str | None = None, timeout: int = 25) -> tuple[int, str, str]:
    req = urllib.request.Request(url, headers={"User-Agent": UA, **({"Accept": accept} if accept else {})})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            ctype = resp.headers.get("Content-Type", "")
            body = resp.read(2_000_000)
            return resp.status, ctype, body.decode("utf-8", "replace") if "pdf" not in ctype else ""
    except urllib.error.HTTPError as exc:
        return exc.code, "", ""


def _arxiv(aid: str) -> tuple[str, str]:
    # Every arXiv paper has a DataCite DOI; doi.org answers without the export API's
    # aggressive 429 throttling, so ask it first and fall back to arXiv itself.
    title, _ = _doi(f"10.48550/arXiv.{aid}")
    if title:
        return title, "doi.org (DataCite)"
    # arXiv asks for one request every three seconds and sheds bursts with a 429; back off.
    for wait in (3, 6, 12, 24):
        time.sleep(wait)
        status, _, body = _get(f"https://export.arxiv.org/api/query?id_list={aid}")
        m = re.search(r"<entry>.*?<title>(.*?)</title>", body, re.S)
        if m:
            return " ".join(m.group(1).split()), "export.arxiv.org"
        if status == 200:  # answered, and there is no such paper
            break
    return "", "export.arxiv.org"


def _doi(doi: str) -> tuple[str, str]:
    status, _, body = _get(f"https://doi.org/{doi}", accept="application/vnd.citationstyles.csl+json")
    if status == 200:
        try:
            title = json.loads(body).get("title") or ""
            if isinstance(title, list):
                title = title[0] if title else ""
            return " ".join(html.unescape(str(title)).split()), "doi.org"
        except json.JSONDecodeError:
            pass
    return "", "doi.org"


def _isbn(isbn: str) -> tuple[str, str]:
    status, _, body = _get(f"https://openlibrary.org/isbn/{isbn}.json")
    if status == 200:
        return str(json.loads(body).get("title", "")), "openlibrary.org"
    return "", "openlibrary.org"


def _url(url: str) -> tuple[str, str]:
    status, ctype, body = _get(url)
    if status != 200:
        return "", f"HTTP {status}"
    host = re.sub(r"^https?://([^/]+).*$", r"\1", url)
    if "pdf" in ctype:
        return f"[PDF] {url.rsplit('/', 1)[-1]}", host
    m = re.search(r"<title[^>]*>(.*?)</title>", body, re.S | re.I)
    return (" ".join(html.unescape(m.group(1)).split()) if m else f"[{ctype or 'page'}]"), host


def resolve(ref: str) -> tuple[str, str]:
    kind, _, value = ref.partition(":")
    return {"arXiv": _arxiv, "doi": _doi, "isbn": _isbn, "url": _url}[kind](value)


def spine_refs() -> list[str]:
    """Every handle any claim or work names, in file order."""
    refs: list[str] = []
    for c in yaml.safe_load((ROOT / "data/claims.yml").read_text())["claims"]:
        refs += extract_refs(c.get("source"))
    for w in yaml.safe_load((ROOT / "data/works.yml").read_text())["works"]:
        refs += extract_refs(work_source(w))
    return list(dict.fromkeys(refs))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--refs", nargs="+", help="look these handles up and print; record nothing")
    args = ap.parse_args()

    if args.refs:
        for ref in args.refs:
            title, via = resolve(ref)
            print(f"{'✓' if title else '✗'} {ref}  [{via}]  {title}")
        return 0

    rows = (yaml.safe_load(RESOLUTIONS.read_text()) or {}).get("resolutions", []) if RESOLUTIONS.exists() else []
    known = index_resolutions(rows)
    todo = [r for r in spine_refs() if r not in known]
    today = dt.date.today().isoformat()
    failed: list[str] = []
    for ref in todo:
        title, via = resolve(ref)
        if title:
            rows.append({"ref": ref, "title": title, "via": via, "checked": today})
            print(f"✓ {ref}  {title}")
        else:
            failed.append(f"{ref} ({via})")
            print(f"✗ {ref}  [{via}] — no title came back", file=sys.stderr)
    rows.sort(key=lambda r: r["ref"])
    RESOLUTIONS.write_text(HEADER + "\n" + yaml.safe_dump({"resolutions": rows}, sort_keys=False, allow_unicode=True, width=100))
    print(f"\nresolved {len(todo) - len(failed)}/{len(todo)} new handle(s); {len(rows)} on record")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
